[package]
name = "simple-kemeleon"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "kemeleon"
harness = false
